name: Parallel Jobs

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: build
      run: sleep 10
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: sleep 10
  Lint:
    runs-on: ubuntu-latest
    steps:
    - name: lint
      run: sleep 10
