name: Triggers

on:
  push:
    branches: [main]
    paths: ['src/**']
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Env'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - Stage
        - prod
      message:
        description: custom
        required: false
        default: hello World
        type: string

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: list files
      run: |
        echo "Current Directory: $(pwd)"
        ls -la
